### ISSUE TITLE
Docker (Windows): Program crashes when renaming book containing "\"

### ISSUE THREAD

**Issue by rune3132** [na--/ebook-tools#2]
The title says it all, my specific case was "Debbie Macomber - [The Manning Men #3] - The Manning Grooms - Bride on the Loose\Same Time, Next Year (2008) [9780778326021]"

**Comment by na--** [comment]
I'll try to debug this tomorrow, though it'll be difficult without a windows machine. Can you tell me the exact error and filename/line number if possible?

**Comment by rune3132** [comment]
Of course. I would imagine the problem being rename-calibre-library.sh trying to rename the file to a name that includes invalid characters, and not being able to handle the error. Here is a screenshot of the error when it happened to another file.
![image](https://user-images.githubusercontent.com/12607046/32985931-6ed531d6-ccc6-11e7-88e4-914d7724acf6.png)

**Comment by na--** [comment]
I saw why this happens. I'll either push a quick fix soon or I'll implement the second item from the roadmap ("Add options for modifying different metadata fields before renaming the files") that will also fix this and other similar issues.

**Comment by na--** [comment]
@rune3132 : please test this, it should be fixed in the latest version as well. I chose the quick and dirty solution because I won't have the free time to implement anything better in the next few days. Please reopen the issue if I haven't managed to fix it.
